### ISSUE TITLE
Wallet Already Exists Checks

### ISSUE THREAD

**Issue by kespinola** [holaplex/hub-treasuries#46]
## Issue
Trying to create a wallet for a customer that already has the asset type results in ID missing error.

```json
{
 "data": null,
 "errors": [
  {
   "message": "missing field `id` at line 1 column 74",
   "locations": [
    {
     "line": 1,
     "column": 10
    }
   ],
   "path": [
    "createCustomerWallet"
   ]
  }
 ]
}
```

## Desire
The `createCustomerWallet` mutation should check if the asset type already exists for the customer before trying to create and respond with error "asset type already exists" error when the database already has a wallet for the customer.

**Comment by imabdulbasit** [comment]
https://github.com/holaplex/hub-treasuries/pull/69
